package com.ly.mybatis.mapper;

import com.ly.mybatis.pojo.Emp;
import com.ly.mybatis.pojo.EmpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

//下面的条件是指：任意需求，大于小于，模糊查询等
public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     * 根据条件获取总记录数
     * @mbggenerated Sat Jun 11 09:59:04 CST 2022
     */
    int countByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     * 根据条件删除
     * @mbggenerated Sat Jun 11 09:59:04 CST 2022
     */
    int deleteByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Jun 11 09:59:04 CST 2022
     */
    int deleteByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     * 普通添加（如果属性中有值null，也会被添加到字段中）
     * @mbggenerated Sat Jun 11 09:59:04 CST 2022
     */
    int insert(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     * 选择性添加 （如果属性中有值null，不会被添加到字段中，只会添加属性值不为空的）
     * @mbggenerated Sat Jun 11 09:59:04 CST 2022
     */
    int insertSelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     * 根据条件查询
     * @mbggenerated Sat Jun 11 09:59:04 CST 2022
     */
    List<Emp> selectByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Jun 11 09:59:04 CST 2022
     */
    Emp selectByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     * 根据条件选择性修改 （如果属性中有值null，不会被添加到字段中）
     * @mbggenerated Sat Jun 11 09:59:04 CST 2022
     */
    int updateByExampleSelective(@Param("record") Emp record, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     * 根据条件修改 （如果属性中有值null，也会被添加到字段中）
     * @mbggenerated Sat Jun 11 09:59:04 CST 2022
     */
    int updateByExample(@Param("record") Emp record, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     * （如果属性中有值null，不会被添加到字段中）
     * @mbggenerated Sat Jun 11 09:59:04 CST 2022
     */
    int updateByPrimaryKeySelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     * （如果属性中有值null，也会被添加到字段中）
     * @mbggenerated Sat Jun 11 09:59:04 CST 2022
     */
    int updateByPrimaryKey(Emp record);
}